apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  selector:
    app: nginx
  type: LoadBalancer      # ArgoCD will manage; use LoadBalancer if you want direct access
  ports:
    - port: 80
      targetPort: 80